In [51]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [52]:
X = np.array([[1,1],[1,4],[2,2],[2,3]])
X

array([[1, 1],
       [1, 4],
       [2, 2],
       [2, 3]])

In [53]:
y = np.dot(X, np.array([1,2])) + 7
y

array([10, 16, 13, 15])

In [54]:
regr = LinearRegression(
   fit_intercept = True, normalize = True, copy_X = True, n_jobs = 2
).fit(X,y)
regr.predict(np.array([[12,15]]))

array([49.])

In [55]:
regr.score(X,y)

1.0

In [56]:
regr.coef_

array([1., 2.])

In [57]:
regr.intercept_

7.0